name: learn-github-actions
on: [push]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: avakar/create-deployment@v1
        with:
          auto_merge: true
          required_contexts: false
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
